server:
  use-forward-headers: true
  
security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'
        
facebook:
  client:
    clientId: 1901152120176408
    clientSecret: 3901ab7f2d8593f447b2449a60265f37
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

logging:
  file: logs/p2f-auth.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d : %msg%n"
  level:
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    org.springframework.security: DEBUG